version: '3.7'
services:
    nginx:
        image: ajdinmore/nginx
        tty:   true
        volumes: [ ./test:/app/public ]
        ports: [ '80:80' ]
        build:
            context: ./nginx

    php:
        image: ajdinmore/php:${PHP_VERSION:-8.2}-${TARGET:-fpm}
        tty:   true
        volumes: [ ./test:/app/public ]
        build:
            context: ./php
            target:  ${TARGET:-fpm}
            args:
                PHP_VERSION: ${PHP_VERSION:-8.2}
