version: '3.7'
services:
    nginx:
        image: 'ajdinmore/nginx'
        tty:   true
        volumes: [ './test:/app/public' ]
        ports: [ '80:80' ]
        build:
            context: './nginx'

    php:
        image: 'ajdinmore/php:${PHP_VERSION}-${TARGET}'
        tty:   true
        volumes: [ './test:/app/public' ]
        extra_hosts: [ 'host.docker.internal:host-gateway' ]
        build:
            context: './php'
            target:  $TARGET
            args:
                PHP_VERSION:    $PHP_VERSION
                DEBIAN_RELEASE: 'bullseye'
